name:                cannelle
version:             0.10.5.3
github:              "whatsupfudd/cannelle"
license:             BSD3
author:              "Hugo DesRosiers"
maintainer:          "hugo.desrosiers@boardingcities.com"
copyright:           "Boarding Cities"

extra-source-files:
- README.md

description: Forked from the Ginger project. Please see the README on GitHub at <https://github.com/hugodrw/fudd/cannelle>

dependencies:
  - base >=4.8 && <5
  - aeson >=1.4.2.0 && <2.3
  - aeson-pretty >=0.8.7 && <0.9
  - bytestring >=0.10.8.2 && <0.12
  - containers >=0.6.4 && <0.7
  - data-default >= 0.5 && <0.8
  - filepath >= 1.3 && <1.5
  - http-types >= 0.8 && (< 0.11 || >= 0.12) && <0.13
  - mtl >= 2.2 && <2.4
  - parsec >= 3.0 && <3.2
  - regex-tdfa >=1.2.3 && <=1.4
  - safe >= 0.3 && <0.4
  - scientific >= 0.3 && <0.4
  - text >=1.2.3.1 && <2.1
  - time >= 0.1.6.0 && <1.13
  - transformers >= 0.3 && <0.7
  - unordered-containers >= 0.2.5 && <0.3
  - utf8-string >=1.0.1.1 && <1.1
  - vector >=0.12.0.2 && <0.14
  # Newer stuff
  - megaparsec
  - cryptohash-md5
  - parser-combinators
  # For parsing programming languages:
  - tree-sitter
  - tree-sitter-haskell
  - tree-sitter-php
  # For PHP:
  - deepseq


default-extensions:
- OverloadedStrings
- DuplicateRecordFields
- OverloadedRecordDot


library:
  source-dirs: src

executables:
  cannelle:
    main: CannelleCLI.hs
    source-dirs: cli
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
      - cannelle
      - optparse-applicative >=0.14.3.0 && <0.19
      - process >=1.6.5.0 && <1.7
      - yaml >=0.11.0.0 && <0.12

tests:
  cannelle-test:
    main: Spec.hs
    source-dirs: test

